# Generated by Django 4.1.2 on 2022-11-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id_contactanos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('numero_cel', models.IntegerField(null=True)),
            ],
        ),
    ]
