# Generated by Django 4.1.2 on 2022-11-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contactanos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactanos',
            name='numero_cel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
