# Generated by Django 4.1.2 on 2022-11-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_contactanos_numero_cel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('numero_cel', models.CharField(max_length=50, null=True)),
                ('num_personas', models.IntegerField()),
                ('fecha', models.CharField(max_length=50, null=True)),
                ('hora', models.CharField(max_length=50, null=True)),
                ('comida_pref', models.CharField(max_length=50, null=True)),
                ('ocasion', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
