# Generated by Django 4.1.2 on 2022-11-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_reservacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
